AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Run Forex algorithm
Resources:
  algo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      MemorySize: 256
      CodeUri: ./
      Events:
        RunEveryMinute:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  SNSSubscriptionAlgo:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: arn:aws:sns:us-east-2:123188106252:newMarketData
      Endpoint: arn:aws:lambda:us-east-2:123188106252:function:algoStack-algo-VN0EFAQDGH8U
      Protocol: lambda
